// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250216042916_GetPersons_StoredProcedure")]
    partial class GetPersons_StoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = new Guid("d761edb1-ba5c-4220-9065-f131048e2f85"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryID = new Guid("8b47d7f5-aac7-48a5-9321-099e3e9cb322"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryID = new Guid("4d01475e-2525-4c94-960c-f4595c3ee212"),
                            CountryName = "UK"
                        },
                        new
                        {
                            CountryID = new Guid("455d502d-640b-4d78-af5d-4ff6a93acc2c"),
                            CountryName = "India"
                        },
                        new
                        {
                            CountryID = new Guid("307dbf16-e6f6-40c4-9999-d78687571605"),
                            CountryName = "Australia"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.HasKey("PersonID");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = new Guid("0e04232b-e9ec-4721-9909-496cb40a7245"),
                            Address = "a0858 Novick Terrace",
                            CountryID = new Guid("d761edb1-ba5c-4220-9065-f131048e2f85"),
                            DateOfBirth = new DateTime(1923, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aguste@booking.com",
                            Gender = "Male",
                            PersonName = "Aguste",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("80ca16b9-1b8c-4815-9f5a-ddb5823243b7"),
                            Address = "b0858 Novick Terrace",
                            CountryID = new Guid("8b47d7f5-aac7-48a5-9321-099e3e9cb322"),
                            DateOfBirth = new DateTime(1963, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sam@booking.com",
                            Gender = "Male",
                            PersonName = "Sam",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("bb6d1d8d-f849-4cbb-9117-8108d2c2992c"),
                            Address = "d0858 Novick Terrace",
                            CountryID = new Guid("4d01475e-2525-4c94-960c-f4595c3ee212"),
                            DateOfBirth = new DateTime(1994, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sundar@booking.com",
                            Gender = "Male",
                            PersonName = "Sundar",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("35f68dc8-ddf0-4e02-b4d9-9b74195f26ae"),
                            Address = "c0858 Novick Terrace",
                            CountryID = new Guid("d761edb1-ba5c-4220-9065-f131048e2f85"),
                            DateOfBirth = new DateTime(1993, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ramesh@booking.com",
                            Gender = "Male",
                            PersonName = "Ramesh",
                            ReceiveNewsLetters = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
